;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagRedirects=(OldTagName="Ability.Type.Action.Locomotion.Sprint_Turn_180",NewTagName="Ability.Type.Action.Locomotion.TurnBack")
+GameplayTagRedirects=(OldTagName="Ability.Type.Action.Locomotion.TurnBack",NewTagName="Ability.Type.Action.Movement.TurnBack")
+GameplayTagRedirects=(OldTagName="Ability.Type.Action.Locomotion",NewTagName="Ability.Type.Action.Movement")
+GameplayTagRedirects=(OldTagName="Event.Movement.AccelerationChanged",NewTagName="Event.Movement.AccelerationStateChanged")
+GameplayTagRedirects=(OldTagName="Event.Ability.Combo.Normal.Close",NewTagName="Event.Ability.State.Combo.Normal.Close")
+GameplayTagRedirects=(OldTagName="Event.Ability.Combo.Normal.Open",NewTagName="Event.Ability.State.Combo.Normal.Open")
+GameplayTagRedirects=(OldTagName="Event.Ability.Combo.Normal",NewTagName="Event.Ability.State.Combo.Normal")
+GameplayTagRedirects=(OldTagName="Event.Ability.Combo",NewTagName="Event.Ability.State.Combo")
+GameplayTagRedirects=(OldTagName="Ability.State.Recovery",NewTagName="Ability.Phase.Recovery")
+GameplayTagRedirects=(OldTagName="Ability.State",NewTagName="Ability.Phase")
+GameplayTagRedirects=(OldTagName="Event.Ability.State.Recovery",NewTagName="Event.Ability.Phase.Recovery")
+GameplayTagRedirects=(OldTagName="Event.Ability.State",NewTagName="Event.Ability.Phase")
+GameplayTagRedirects=(OldTagName="Gameplay.HitReact.Launcher",NewTagName="Gameplay.HitReact.Launch")
+GameplayTagRedirects=(OldTagName="Gameplay.HitReact.Shake.Knockback",NewTagName="Gameplay.HitReact.Shake.Knockback")
+GameplayTagList=(Tag="Ability.Phase.Recovery",DevComment="")
+GameplayTagList=(Tag="Ability.Type.Action.Attack",DevComment="")
+GameplayTagList=(Tag="Ability.Type.Action.Jump",DevComment="")
+GameplayTagList=(Tag="Ability.Type.Action.Movement.StrafeMove",DevComment="")
+GameplayTagList=(Tag="Ability.Type.Action.Movement.TurnBack",DevComment="")
+GameplayTagList=(Tag="Event.Ability.Phase.Recovery",DevComment="")
+GameplayTagList=(Tag="Event.Bullet.DestroyBullet",DevComment="")
+GameplayTagList=(Tag="Event.Bullet.ProcessManualHits",DevComment="")
+GameplayTagList=(Tag="Event.Bullet.SpawnBullet",DevComment="")
+GameplayTagList=(Tag="Event.Movement.AccelerationStateChanged",DevComment="")
+GameplayTagList=(Tag="Event.Movement.Jump",DevComment="")
+GameplayTagList=(Tag="Event.Movement.StrafeMove",DevComment="")
+GameplayTagList=(Tag="Gameplay.HitReact.Knockback",DevComment="")
+GameplayTagList=(Tag="Gameplay.HitReact.Launch",DevComment="")
+GameplayTagList=(Tag="Gameplay.HitReact.Normal",DevComment="")
+GameplayTagList=(Tag="Gameplay.HitReact.Shake",DevComment="")
+GameplayTagList=(Tag="InputCommand.Attack.Light.Hold",DevComment="")
+GameplayTagList=(Tag="InputCommand.Jump",DevComment="")
+GameplayTagList=(Tag="InputTag.Attack.Light",DevComment="")
+GameplayTagList=(Tag="InputTag.Attack.Light.Hold",DevComment="")
+GameplayTagList=(Tag="InputTag.Jump",DevComment="")
+GameplayTagList=(Tag="InputTag.StrafeMove",DevComment="")
+GameplayTagList=(Tag="InputTag.TurnBack",DevComment="")

